[package]
name = "edwards-schnorr"
version = "0.1.0"
edition = "2021"

[dependencies]
ed25519-dalek = { version = "2", features = ["digest", "hazmat"] }
curve25519-dalek = "4"
rand = "0.8"

hex = "0.4"
