[package]
name = "eddsa"
version = "0.1.0"
edition = "2021"

[dependencies]
ed25519 = { package = "ed25519-dalek", version = "2", features = ["rand_core", "hazmat"] }
rand_core = { version = "0.6", features = ["getrandom"] }
hex = "0.4"
