name: Tests

on:
  pull_request:
    branches: [ "*" ]

jobs:
  check_readme:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
    - name: Install toc-markdown
      run: npm install -g markdown-toc
    - name: Check that readme matches the template
      run: |
        cp README.md README-copy.md
        ./compile_readme.sh
        diff README.md README-copy.md
  compile_rust:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
      with:
        cache-on-failure: "true"
    - name: Build
      run: cargo build --release --all-features
    - name: Rename binary
      run: mv target/release/edwards-schnorr sign-rs
    - uses: actions/upload-artifact@v4
      with:
        name: sign-rs
        path: sign-rs
        if-no-files-found: error
    - uses: actions/upload-artifact@v4
      with:
        name: eddsa
        path: target/release/eddsa
        if-no-files-found: error
  compile_go:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: (cd go; go build .)
    - name: Rename binary
      run: mv go/sign go/sign-go
    - uses: actions/upload-artifact@v4
      with:
        name: sign-go
        path: go/sign-go
        if-no-files-found: error
  test_rust:
    runs-on: ubuntu-latest
    needs: compile_rust
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: eddsa
    - uses: actions/download-artifact@v4
      with:
        name: sign-rs
    - name: Set file permissions
      run: chmod +x eddsa sign-rs
    - name: Outputs correct signature
      run: |
        eddsa_sk=$(./eddsa keygen)
        pk=$(./eddsa get-public-key $eddsa_sk)

        schnorr_sk=$(./eddsa to-schnorr-key $eddsa_sk)
        msg="hello!"
        sig=$(./sign-rs $schnorr_sk $msg)

        ./eddsa verify $pk $msg $sig
  test_go:
    runs-on: ubuntu-latest
    needs: [compile_rust, compile_go]
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: eddsa
    - uses: actions/download-artifact@v4
      with:
        name: sign-go
    - name: Set file permissions
      run: chmod +x eddsa sign-go
    - name: Outputs correct signature
      run: |
        eddsa_sk=$(./eddsa keygen)
        pk=$(./eddsa get-public-key $eddsa_sk)

        schnorr_sk=$(./eddsa to-schnorr-key $eddsa_sk)
        msg="hello!"
        sig=$(./sign-go -secret-key $schnorr_sk -message $msg)

        ./eddsa verify $pk $msg $sig
    
